const crypto = require('crypto');

function installV2Api(app, db, { requireLogin, requireOwner }) {
  const shopId = req => Number(req.session.employee.shop_id);
  const employeeId = req => Number(req.session.employee.id);
  const owns = (table, id, sid) => db.prepare(`SELECT * FROM ${table} WHERE id = ? AND shop_id = ?`).get(id, sid);
  const audit = (sid, eid, action, entityType, entityId, details = null) => db.prepare(`INSERT INTO audit_log (shop_id, employee_id, action, entity_type, entity_id, details) VALUES (?, ?, ?, ?, ?, ?)`).run(sid, eid, action, entityType, entityId || null, details ? JSON.stringify(details) : null);
  const token = () => crypto.randomBytes(24).toString('hex');

  app.get('/api/v2/overview', requireLogin, (req, res) => {
    const sid = shopId(req); const one = sql => db.prepare(sql).get(sid).n;
    res.json({activeRepairOrders:one(`SELECT COUNT(*) n FROM repair_orders WHERE shop_id=? AND status!='completed'`),inspections:one(`SELECT COUNT(*) n FROM dvi_inspections WHERE shop_id=? AND status!='completed'`),deferred:one(`SELECT COUNT(*) n FROM deferred_services WHERE shop_id=? AND status='deferred'`),lowStock:one(`SELECT COUNT(*) n FROM inventory_items WHERE shop_id=? AND active=1 AND quantity<=reorder_level`),techniciansClockedIn:one(`SELECT COUNT(DISTINCT employee_id) n FROM technician_time_entries WHERE shop_id=? AND clock_out IS NULL`)});
  });
  app.get('/api/v2/shop-board', requireLogin, (req,res)=>res.json(db.prepare(`SELECT r.id,r.status,r.workflow_status,r.parts_status,r.promised_at,r.assigned_technician_id,c.name customer_name,v.year,v.make,v.model,e.name technician_name FROM repair_orders r LEFT JOIN customers c ON c.id=r.customer_id LEFT JOIN vehicles v ON v.id=r.vehicle_id LEFT JOIN employees e ON e.id=r.assigned_technician_id WHERE r.shop_id=? AND r.status!='completed' ORDER BY r.created_at`).all(shopId(req))));
  app.patch('/api/v2/repair-orders/:id/workflow', requireLogin,(req,res)=>{const sid=shopId(req),id=Number(req.params.id),allowed=['waiting','assigned','in_progress','waiting_parts','waiting_approval','ready','completed'],status=String(req.body.workflow_status||'');if(!owns('repair_orders',id,sid))return res.status(404).json({error:'Repair order not found.'});if(!allowed.includes(status))return res.status(400).json({error:'Invalid workflow status.'});db.prepare(`UPDATE repair_orders SET workflow_status=? WHERE id=? AND shop_id=?`).run(status,id,sid);audit(sid,employeeId(req),'workflow.update','repair_order',id,{status});res.json({ok:true});});
  app.patch('/api/v2/repair-orders/:id/assign',requireLogin,(req,res)=>{const sid=shopId(req),id=Number(req.params.id),tech=Number(req.body.employee_id||0);if(!owns('repair_orders',id,sid))return res.status(404).json({error:'Repair order not found.'});if(!db.prepare(`SELECT id FROM employees WHERE id=? AND shop_id=? AND active=1`).get(tech,sid))return res.status(400).json({error:'Technician not found.'});db.prepare(`UPDATE repair_orders SET assigned_technician_id=?,workflow_status=CASE WHEN workflow_status='waiting' THEN 'assigned' ELSE workflow_status END WHERE id=? AND shop_id=?`).run(tech,id,sid);audit(sid,employeeId(req),'technician.assign','repair_order',id,{employee_id:tech});res.json({ok:true});});

  app.get('/api/v2/technician-performance',requireLogin,requireOwner,(req,res)=>{const sid=shopId(req);res.json(db.prepare(`SELECT e.id,e.name,COUNT(DISTINCT t.repair_order_id) jobs,COALESCE(SUM(t.minutes),0) actual_minutes,COALESCE(SUM(roi.labor_hours),0) billed_hours FROM employees e LEFT JOIN technician_time_entries t ON t.employee_id=e.id AND t.shop_id=e.shop_id LEFT JOIN repair_order_items roi ON roi.repair_order_id=t.repair_order_id WHERE e.shop_id=? AND e.active=1 GROUP BY e.id,e.name ORDER BY e.name`).all(sid));});

  app.get('/api/v2/inventory',requireLogin,(req,res)=>res.json(db.prepare(`SELECT i.*,v.name vendor_name FROM inventory_items i LEFT JOIN vendors v ON v.id=i.vendor_id WHERE i.shop_id=? AND i.active=1 ORDER BY i.description`).all(shopId(req))));
  app.post('/api/v2/inventory',requireLogin,requireOwner,(req,res)=>{const sid=shopId(req);const info=db.prepare(`INSERT INTO inventory_items(shop_id,vendor_id,sku,part_number,description,quantity,reorder_level,cost,sell_price,location)VALUES(?,?,?,?,?,?,?,?,?,?)`).run(sid,Number(req.body.vendor_id||0)||null,String(req.body.sku||''),String(req.body.part_number||''),String(req.body.description||'').trim(),Number(req.body.quantity||0),Number(req.body.reorder_level||0),Number(req.body.cost||0),Number(req.body.sell_price||0),String(req.body.location||''));res.json({ok:true,id:info.lastInsertRowid});});
  app.get('/api/v2/vendors',requireLogin,(req,res)=>res.json(db.prepare(`SELECT * FROM vendors WHERE shop_id=? AND active=1 ORDER BY name`).all(shopId(req))));
  app.post('/api/v2/vendors',requireLogin,requireOwner,(req,res)=>{const sid=shopId(req);if(!String(req.body.name||'').trim())return res.status(400).json({error:'Vendor name required.'});const info=db.prepare(`INSERT INTO vendors(shop_id,name,contact_name,phone,email,website,account_number,notes)VALUES(?,?,?,?,?,?,?,?)`).run(sid,String(req.body.name).trim(),String(req.body.contact_name||''),String(req.body.phone||''),String(req.body.email||''),String(req.body.website||''),String(req.body.account_number||''),String(req.body.notes||''));res.json({ok:true,id:info.lastInsertRowid});});
  app.get('/api/v2/purchase-orders',requireLogin,(req,res)=>res.json(db.prepare(`SELECT p.*,v.name vendor_name FROM purchase_orders p LEFT JOIN vendors v ON v.id=p.vendor_id WHERE p.shop_id=? ORDER BY p.created_at DESC`).all(shopId(req))));
  app.post('/api/v2/purchase-orders',requireLogin,requireOwner,(req,res)=>{const sid=shopId(req),vendor=Number(req.body.vendor_id||0)||null;if(vendor&&!owns('vendors',vendor,sid))return res.status(400).json({error:'Vendor not found.'});const po=`PO-${Date.now().toString().slice(-8)}`,info=db.prepare(`INSERT INTO purchase_orders(shop_id,vendor_id,repair_order_id,po_number,notes)VALUES(?,?,?,?,?)`).run(sid,vendor,Number(req.body.repair_order_id||0)||null,po,String(req.body.notes||''));res.json({ok:true,id:info.lastInsertRowid,po_number:po});});
  app.post('/api/v2/purchase-orders/:id/items',requireLogin,requireOwner,(req,res)=>{const sid=shopId(req),pid=Number(req.params.id);if(!owns('purchase_orders',pid,sid))return res.status(404).json({error:'Purchase order not found.'});const info=db.prepare(`INSERT INTO purchase_order_items(shop_id,purchase_order_id,inventory_item_id,part_number,description,quantity,unit_cost)VALUES(?,?,?,?,?,?,?)`).run(sid,pid,Number(req.body.inventory_item_id||0)||null,String(req.body.part_number||''),String(req.body.description||'').trim(),Number(req.body.quantity||1),Number(req.body.unit_cost||0));res.json({ok:true,id:info.lastInsertRowid});});
  app.patch('/api/v2/purchase-orders/:id/status',requireLogin,requireOwner,(req,res)=>{const sid=shopId(req),id=Number(req.params.id),status=String(req.body.status||'draft');if(!owns('purchase_orders',id,sid))return res.status(404).json({error:'Purchase order not found.'});if(!['draft','ordered','partial','received','cancelled'].includes(status))return res.status(400).json({error:'Invalid status.'});db.prepare(`UPDATE purchase_orders SET status=?,ordered_at=CASE WHEN ?='ordered' THEN CURRENT_TIMESTAMP ELSE ordered_at END,received_at=CASE WHEN ?='received' THEN CURRENT_TIMESTAMP ELSE received_at END WHERE id=? AND shop_id=?`).run(status,status,status,id,sid);res.json({ok:true});});

  app.post('/api/v2/customers/:id/portal-token',requireLogin,(req,res)=>{const sid=shopId(req),cid=Number(req.params.id);if(!owns('customers',cid,sid))return res.status(404).json({error:'Customer not found.'});const value=token();db.prepare(`INSERT INTO customer_portal_tokens(shop_id,customer_id,token,expires_at) VALUES(?,?,?,datetime('now','+90 days'))`).run(sid,cid,value);res.json({ok:true,url:`/customer-portal.html?token=${value}`});});
  app.get('/api/v2/public/portal/:token',(req,res)=>{const access=db.prepare(`SELECT * FROM customer_portal_tokens WHERE token=? AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>CURRENT_TIMESTAMP)`).get(String(req.params.token));if(!access)return res.status(404).json({error:'Portal link is invalid or expired.'});const customer=db.prepare(`SELECT id,name FROM customers WHERE id=? AND shop_id=?`).get(access.customer_id,access.shop_id),shop=db.prepare(`SELECT id,name FROM shops WHERE id=?`).get(access.shop_id),vehicles=db.prepare(`SELECT * FROM vehicles WHERE customer_id=? AND shop_id=?`).all(access.customer_id,access.shop_id),orders=db.prepare(`SELECT id,vehicle_id,status,workflow_status,payment_status,amount_paid,created_at,completed_at FROM repair_orders WHERE customer_id=? AND shop_id=? ORDER BY created_at DESC LIMIT 50`).all(access.customer_id,access.shop_id),deferred=db.prepare(`SELECT id,vehicle_id,description,estimated_total,status,follow_up_date FROM deferred_services WHERE customer_id=? AND shop_id=? AND status IN('deferred','scheduled') ORDER BY created_at DESC`).all(access.customer_id,access.shop_id);res.json({shop,customer,vehicles,orders,deferred});});

  app.get('/api/v2/profitability',requireLogin,requireOwner,(req,res)=>{const sid=shopId(req),row=db.prepare(`SELECT COALESCE(SUM(i.parts),0) parts_sales,COALESCE(SUM(i.parts_cost),0) parts_cost,COALESCE(SUM(i.labor),0) labor_sales,COALESCE(SUM(i.labor_cost),0) labor_cost FROM repair_order_items i JOIN repair_orders r ON r.id=i.repair_order_id WHERE r.shop_id=?`).get(sid),sales=row.parts_sales+row.labor_sales,cost=row.parts_cost+row.labor_cost;res.json({...row,sales,cost,gross_profit:sales-cost,gross_margin:sales?((sales-cost)/sales*100):0});});
  app.get('/api/v2/audit',requireLogin,requireOwner,(req,res)=>res.json(db.prepare(`SELECT a.*,e.name employee_name FROM audit_log a LEFT JOIN employees e ON e.id=a.employee_id WHERE a.shop_id=? ORDER BY a.created_at DESC LIMIT 250`).all(shopId(req))));
}
module.exports={installV2Api};
