const {permissionMiddleware,loadCurrentEmployee}=require('./v2-permissions');
function installV2Alerts(app,db,{requireLogin}){
 if(!app||!db)throw new Error('V2 alerts require app and db.');if(!requireLogin)throw new Error('V2 alerts require login middleware.');
 const requireRepairOrders=permissionMiddleware('repair_orders',db),has=n=>Boolean(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(n)),validId=v=>Number.isInteger(v)&&v>0;
 app.get('/api/v2/alerts',requireLogin,requireRepairOrders,(req,res)=>{try{
  res.set('Cache-Control','no-store, private, max-age=0');res.set('Pragma','no-cache');res.set('Expires','0');
  const employee=req.v2Employee||loadCurrentEmployee(db,req.session?.employee),s=Number(employee?.shop_id||0),e=Number(employee?.id||0);if(!employee||!validId(s)||!validId(e))return res.status(401).json({error:'Employee session is no longer valid for this shop.'});req.v2Employee=employee;req.v2ShopId=s;
  const alerts=[];
  if(has('v2_tasks'))db.prepare("SELECT id,repair_order_id,title,priority,due_at FROM v2_tasks WHERE shop_id=? AND status='open' AND due_at IS NOT NULL AND datetime(due_at)<datetime('now') ORDER BY due_at LIMIT 50").all(s).forEach(x=>alerts.push({severity:x.priority==='urgent'?'critical':'warning',type:'overdue_task',title:'Overdue task: '+x.title,repair_order_id:x.repair_order_id,when:x.due_at,source_id:x.id}));
  if(has('v2_ro_promises'))db.prepare("SELECT p.repair_order_id,p.promised_at,c.name customer_name FROM v2_ro_promises p JOIN repair_orders r ON r.id=p.repair_order_id AND r.shop_id=p.shop_id JOIN customers c ON c.id=r.customer_id AND c.shop_id=r.shop_id WHERE p.shop_id=? AND datetime(p.promised_at)<datetime('now') AND COALESCE(r.status,'')!='completed' ORDER BY p.promised_at LIMIT 50").all(s).forEach(x=>alerts.push({severity:'critical',type:'missed_promise',title:'Promised time passed: '+x.customer_name,repair_order_id:x.repair_order_id,when:x.promised_at}));
  if(has('v2_ro_blockers'))db.prepare("SELECT id,repair_order_id,reason,created_at FROM v2_ro_blockers WHERE shop_id=? AND status='open' AND datetime(created_at)<=datetime('now','-4 hours') ORDER BY created_at LIMIT 50").all(s).forEach(x=>alerts.push({severity:'warning',type:'aging_blocker',title:'Blocker open 4+ hours: '+x.reason,repair_order_id:x.repair_order_id,when:x.created_at,source_id:x.id}));
  if(has('v2_parts_requests'))db.prepare("SELECT id,repair_order_id,description,status,updated_at FROM v2_parts_requests WHERE shop_id=? AND status IN ('requested','ordered') AND datetime(updated_at)<=datetime('now','-24 hours') ORDER BY updated_at LIMIT 50").all(s).forEach(x=>alerts.push({severity:'warning',type:'aging_part',title:'Parts request needs follow-up: '+x.description,repair_order_id:x.repair_order_id,when:x.updated_at,source_id:x.id}));
  const order={critical:0,warning:1,info:2};alerts.sort((a,b)=>order[a.severity]-order[b.severity]||String(a.when||'').localeCompare(String(b.when||'')));return res.json({count:alerts.length,critical:alerts.filter(x=>x.severity==='critical').length,alerts});
 }catch(err){console.error('Garavex V2 alerts error:',err);return res.status(500).json({error:'Unable to load alerts.'});}});
}
module.exports={installV2Alerts};