function installV2Alerts(app,db,{requireLogin}){
 const sid=req=>Number(req.session.employee.shop_id),has=n=>!!db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(n);
 app.get('/api/v2/alerts',requireLogin,(req,res)=>{const s=sid(req),alerts=[];
  if(has('v2_tasks')) db.prepare("SELECT id,repair_order_id,title,priority,due_at FROM v2_tasks WHERE shop_id=? AND status='open' AND due_at IS NOT NULL AND datetime(due_at)<datetime('now') ORDER BY due_at LIMIT 50").all(s).forEach(x=>alerts.push({severity:x.priority==='urgent'?'critical':'warning',type:'overdue_task',title:'Overdue task: '+x.title,repair_order_id:x.repair_order_id,when:x.due_at,source_id:x.id}));
  if(has('v2_ro_promises')) db.prepare("SELECT p.repair_order_id,p.promised_at,c.name customer_name FROM v2_ro_promises p JOIN repair_orders r ON r.id=p.repair_order_id AND r.shop_id=p.shop_id JOIN customers c ON c.id=r.customer_id WHERE p.shop_id=? AND datetime(p.promised_at)<datetime('now') AND COALESCE(r.status,'')!='completed' ORDER BY p.promised_at LIMIT 50").all(s).forEach(x=>alerts.push({severity:'critical',type:'missed_promise',title:'Promised time passed: '+x.customer_name,repair_order_id:x.repair_order_id,when:x.promised_at}));
  if(has('v2_ro_blockers')) db.prepare("SELECT b.id,b.repair_order_id,b.reason,b.created_at FROM v2_ro_blockers b WHERE b.shop_id=? AND b.status='open' AND datetime(b.created_at)<=datetime('now','-4 hours') ORDER BY b.created_at LIMIT 50").all(s).forEach(x=>alerts.push({severity:'warning',type:'aging_blocker',title:'Blocker open 4+ hours: '+x.reason,repair_order_id:x.repair_order_id,when:x.created_at,source_id:x.id}));
  if(has('v2_parts_requests')) db.prepare("SELECT id,repair_order_id,description,status,updated_at FROM v2_parts_requests WHERE shop_id=? AND status IN ('requested','ordered') AND datetime(updated_at)<=datetime('now','-24 hours') ORDER BY updated_at LIMIT 50").all(s).forEach(x=>alerts.push({severity:'warning',type:'aging_part',title:'Parts request needs follow-up: '+x.description,repair_order_id:x.repair_order_id,when:x.updated_at,source_id:x.id}));
  const order={critical:0,warning:1,info:2};alerts.sort((a,b)=>order[a.severity]-order[b.severity]||String(a.when).localeCompare(String(b.when)));res.json({count:alerts.length,critical:alerts.filter(x=>x.severity==='critical').length,alerts});
 });
}
module.exports={installV2Alerts};
