const {permissionMiddleware,loadCurrentEmployee}=require('./v2-permissions');
function installV2Alerts(app,db,{requireLogin}){
 if(!app||!db)throw new Error('V2 alerts require app and db.');if(!requireLogin)throw new Error('V2 alerts require login middleware.');
 const requireRepairOrders=permissionMiddleware('repair_orders',db),has=n=>Boolean(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(n)),validId=v=>Number.isInteger(v)&&v>0;
 const clean=(v,max=240)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,max);
 app.get('/api/v2/alerts',requireLogin,requireRepairOrders,(req,res)=>{try{
  res.set('Cache-Control','no-store, private, max-age=0');res.set('Pragma','no-cache');res.set('Expires','0');res.set('X-Content-Type-Options','nosniff');
  const employee=req.v2Employee||loadCurrentEmployee(db,req.session?.employee),s=Number(employee?.shop_id||0),e=Number(employee?.id||0);if(!employee||!validId(s)||!validId(e))return res.status(401).json({error:'Employee session is no longer valid for this shop.'});
  const live=loadCurrentEmployee(db,req.session?.employee);if(!live||Number(live.id)!==e||Number(live.shop_id)!==s)return res.status(401).json({error:'Employee session is no longer valid for this shop.'});req.v2Employee=live;req.v2ShopId=Number(live.shop_id);
  const alerts=[],push=a=>{if(alerts.length<200)alerts.push({...a,title:clean(a.title,300),when:a.when?clean(a.when,80):null});};
  if(has('v2_tasks'))db.prepare("SELECT t.id,t.repair_order_id,t.title,t.priority,t.due_at FROM v2_tasks t LEFT JOIN repair_orders r ON r.id=t.repair_order_id AND r.shop_id=t.shop_id LEFT JOIN customers c ON c.id=r.customer_id AND c.shop_id=r.shop_id LEFT JOIN vehicles v ON v.id=r.vehicle_id AND v.shop_id=r.shop_id WHERE t.shop_id=? AND t.status='open' AND t.due_at IS NOT NULL AND datetime(t.due_at)<datetime('now') AND (t.repair_order_id IS NULL OR (r.id IS NOT NULL AND c.id IS NOT NULL AND (r.vehicle_id IS NULL OR v.id IS NOT NULL))) ORDER BY t.due_at LIMIT 50").all(s).forEach(x=>push({severity:x.priority==='urgent'?'critical':'warning',type:'overdue_task',title:'Overdue task: '+clean(x.title),repair_order_id:x.repair_order_id,when:x.due_at,source_id:x.id}));
  if(has('v2_ro_promises'))db.prepare("SELECT p.id,p.repair_order_id,p.promised_at,c.name customer_name FROM v2_ro_promises p JOIN repair_orders r ON r.id=p.repair_order_id AND r.shop_id=p.shop_id JOIN customers c ON c.id=r.customer_id AND c.shop_id=r.shop_id LEFT JOIN vehicles v ON v.id=r.vehicle_id AND v.shop_id=r.shop_id WHERE p.shop_id=? AND (r.vehicle_id IS NULL OR v.id IS NOT NULL) AND datetime(p.promised_at)<datetime('now') AND LOWER(COALESCE(r.status,''))!='completed' AND LOWER(COALESCE(r.workflow_status,''))!='delivered' ORDER BY p.promised_at LIMIT 50").all(s).forEach(x=>push({severity:'critical',type:'missed_promise',title:'Promised time passed: '+clean(x.customer_name),repair_order_id:x.repair_order_id,when:x.promised_at,source_id:x.id}));
  if(has('v2_ro_blockers'))db.prepare("SELECT b.id,b.repair_order_id,b.reason,b.created_at FROM v2_ro_blockers b JOIN repair_orders r ON r.id=b.repair_order_id AND r.shop_id=b.shop_id JOIN customers c ON c.id=r.customer_id AND c.shop_id=r.shop_id LEFT JOIN vehicles v ON v.id=r.vehicle_id AND v.shop_id=r.shop_id WHERE b.shop_id=? AND (r.vehicle_id IS NULL OR v.id IS NOT NULL) AND b.status='open' AND datetime(b.created_at)<=datetime('now','-4 hours') AND LOWER(COALESCE(r.status,''))!='completed' AND LOWER(COALESCE(r.workflow_status,''))!='delivered' ORDER BY b.created_at LIMIT 50").all(s).forEach(x=>push({severity:'warning',type:'aging_blocker',title:'Blocker open 4+ hours: '+clean(x.reason),repair_order_id:x.repair_order_id,when:x.created_at,source_id:x.id}));
  if(has('v2_parts_requests'))db.prepare("SELECT p.id,p.repair_order_id,p.description,p.status,p.updated_at FROM v2_parts_requests p JOIN repair_orders r ON r.id=p.repair_order_id AND r.shop_id=p.shop_id JOIN customers c ON c.id=r.customer_id AND c.shop_id=r.shop_id LEFT JOIN vehicles v ON v.id=r.vehicle_id AND v.shop_id=r.shop_id WHERE p.shop_id=? AND (r.vehicle_id IS NULL OR v.id IS NOT NULL) AND p.status IN ('requested','ordered') AND datetime(p.updated_at)<=datetime('now','-24 hours') AND LOWER(COALESCE(r.status,''))!='completed' AND LOWER(COALESCE(r.workflow_status,''))!='delivered' ORDER BY p.updated_at LIMIT 50").all(s).forEach(x=>push({severity:'warning',type:'aging_part',title:'Parts request needs follow-up: '+clean(x.description),repair_order_id:x.repair_order_id,when:x.updated_at,source_id:x.id}));
  const order={critical:0,warning:1,info:2};alerts.sort((a,b)=>order[a.severity]-order[b.severity]||String(a.when||'').localeCompare(String(b.when||'')));return res.json({count:alerts.length,critical:alerts.filter(x=>x.severity==='critical').length,alerts});
 }catch(err){console.error('Garavex V2 alerts error:',err);return res.status(500).json({error:'Unable to load alerts.'});}});
}
module.exports={installV2Alerts};