const {permissionMiddleware}=require('./v2-permissions');
function installV2Keys(app,db,{requireLogin}){
 const sid=req=>Number(req.session.employee.shop_id),eid=req=>Number(req.session.employee.id),requireKeys=permissionMiddleware('keys');
 db.exec(`CREATE TABLE IF NOT EXISTS v2_vehicle_keys(id INTEGER PRIMARY KEY AUTOINCREMENT,shop_id INTEGER NOT NULL,repair_order_id INTEGER NOT NULL,key_tag TEXT,location TEXT,status TEXT NOT NULL DEFAULT 'checked_in',note TEXT,updated_by INTEGER,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,UNIQUE(shop_id,repair_order_id));CREATE INDEX IF NOT EXISTS idx_v2_vehicle_keys_shop_status ON v2_vehicle_keys(shop_id,status);`);
 const allowed=['checked_in','technician','key_board','customer','missing'];
 app.get('/api/v2/keys',requireLogin,requireKeys,(req,res)=>{const s=sid(req);res.json(db.prepare(`SELECT k.*,c.name customer_name,v.year,v.make,v.model,e.name technician_name FROM v2_vehicle_keys k JOIN repair_orders r ON r.id=k.repair_order_id AND r.shop_id=k.shop_id JOIN customers c ON c.id=r.customer_id AND c.shop_id=r.shop_id LEFT JOIN vehicles v ON v.id=r.vehicle_id AND v.shop_id=r.shop_id LEFT JOIN v2_ro_assignments a ON a.repair_order_id=r.id AND a.shop_id=r.shop_id LEFT JOIN employees e ON e.id=a.employee_id AND e.shop_id=r.shop_id WHERE k.shop_id=? AND COALESCE(r.workflow_status,'')!='delivered' ORDER BY CASE k.status WHEN 'missing' THEN 0 WHEN 'technician' THEN 1 ELSE 2 END,k.updated_at DESC`).all(s));});
 app.put('/api/v2/repair-orders/:id/key',requireLogin,requireKeys,(req,res)=>{const s=sid(req),ro=Number(req.params.id),status=String(req.body.status||'checked_in'),tag=String(req.body.key_tag||'').trim().slice(0,100),location=String(req.body.location||'').trim().slice(0,300),note=String(req.body.note||'').trim().slice(0,1000);if(!allowed.includes(status))return res.status(400).json({error:'Invalid key status.'});const order=db.prepare(`SELECT id,workflow_status FROM repair_orders WHERE id=? AND shop_id=?`).get(ro,s);if(!order)return res.status(404).json({error:'Repair order not found.'});if(String(order.workflow_status||'').toLowerCase()==='delivered'&&status!=='customer')return res.status(409).json({error:'Delivered vehicle keys must remain returned to the customer.'});if(status==='missing'&&!note)return res.status(400).json({error:'Add a note describing the missing key situation.'});if(status==='technician'&&!location)return res.status(400).json({error:'Record who or where the technician key is with.'});if(status==='key_board'&&!location)return res.status(400).json({error:'Record the key board location.'});const previous=db.prepare(`SELECT * FROM v2_vehicle_keys WHERE shop_id=? AND repair_order_id=?`).get(s,ro);const tx=db.transaction(()=>{db.prepare(`INSERT INTO v2_vehicle_keys(shop_id,repair_order_id,key_tag,location,status,note,updated_by)VALUES(?,?,?,?,?,?,?) ON CONFLICT(shop_id,repair_order_id) DO UPDATE SET key_tag=excluded.key_tag,location=excluded.location,status=excluded.status,note=excluded.note,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP`).run(s,ro,tag,location,status,note,eid(req));db.prepare(`INSERT INTO audit_log(shop_id,employee_id,action,entity_type,entity_id,details)VALUES(?,?,?,?,?,?)`).run(s,eid(req),'vehicle.key_updated','repair_order',ro,JSON.stringify({previous_status:previous?.status||null,status,key_tag:tag,location,note}));});tx();res.json({ok:true,status});});
}
module.exports={installV2Keys};
