function installV2Loaners(app,db,{requireLogin}){
 const sid=req=>Number(req.session.employee.shop_id),eid=req=>Number(req.session.employee.id);
 db.exec(`CREATE TABLE IF NOT EXISTS v2_loaners(id INTEGER PRIMARY KEY AUTOINCREMENT,shop_id INTEGER NOT NULL,name TEXT NOT NULL,year TEXT,make TEXT,model TEXT,plate TEXT,vin TEXT,status TEXT NOT NULL DEFAULT 'available',active INTEGER NOT NULL DEFAULT 1);CREATE TABLE IF NOT EXISTS v2_loaner_assignments(id INTEGER PRIMARY KEY AUTOINCREMENT,shop_id INTEGER NOT NULL,loaner_id INTEGER NOT NULL,repair_order_id INTEGER NOT NULL,customer_id INTEGER NOT NULL,checked_out_at DATETIME DEFAULT CURRENT_TIMESTAMP,due_back_at DATETIME,returned_at DATETIME,out_mileage INTEGER,out_fuel TEXT,note TEXT,employee_id INTEGER);CREATE INDEX IF NOT EXISTS idx_v2_loaners_shop ON v2_loaners(shop_id,status);CREATE INDEX IF NOT EXISTS idx_v2_loaner_assignments_open ON v2_loaner_assignments(shop_id,returned_at);`);
 app.get('/api/v2/loaners',requireLogin,(req,res)=>{const s=sid(req);const vehicles=db.prepare(`SELECT * FROM v2_loaners WHERE shop_id=? AND active=1 ORDER BY name`).all(s);const open=db.prepare(`SELECT a.*,l.name loaner_name,c.name customer_name,v.year vehicle_year,v.make vehicle_make,v.model vehicle_model FROM v2_loaner_assignments a JOIN v2_loaners l ON l.id=a.loaner_id AND l.shop_id=a.shop_id JOIN customers c ON c.id=a.customer_id JOIN repair_orders r ON r.id=a.repair_order_id AND r.shop_id=a.shop_id LEFT JOIN vehicles v ON v.id=r.vehicle_id WHERE a.shop_id=? AND a.returned_at IS NULL ORDER BY a.due_back_at`).all(s);res.json({vehicles,assignments:open});});
 app.post('/api/v2/loaners',requireLogin,(req,res)=>{const s=sid(req),name=String(req.body.name||'').trim();if(!name)return res.status(400).json({error:'Loaner name is required.'});const info=db.prepare(`INSERT INTO v2_loaners(shop_id,name,year,make,model,plate,vin)VALUES(?,?,?,?,?,?,?)`).run(s,name,String(req.body.year||''),String(req.body.make||''),String(req.body.model||''),String(req.body.plate||''),String(req.body.vin||''));res.json({ok:true,id:info.lastInsertRowid});});
 app.post('/api/v2/loaners/:id/checkout',requireLogin,(req,res)=>{const s=sid(req),loaner=Number(req.params.id),ro=Number(req.body.repair_order_id);const l=db.prepare(`SELECT * FROM v2_loaners WHERE id=? AND shop_id=? AND active=1 AND status='available'`).get(loaner,s);if(!l)return res.status(400).json({error:'Loaner is not available.'});const r=db.prepare(`SELECT id,customer_id FROM repair_orders WHERE id=? AND shop_id=? AND status!='completed'`).get(ro,s);if(!r)return res.status(404).json({error:'Active repair order not found.'});const tx=db.transaction(()=>{db.prepare(`INSERT INTO v2_loaner_assignments(shop_id,loaner_id,repair_order_id,customer_id,due_back_at,out_mileage,out_fuel,note,employee_id)VALUES(?,?,?,?,?,?,?,?,?)`).run(s,loaner,ro,r.customer_id,req.body.due_back_at||null,Number(req.body.out_mileage)||null,String(req.body.out_fuel||''),String(req.body.note||''),eid(req));db.prepare(`UPDATE v2_loaners SET status='out' WHERE id=? AND shop_id=?`).run(loaner,s);});tx();res.json({ok:true});});
 app.patch('/api/v2/loaner-assignments/:id/return',requireLogin,(req,res)=>{const s=sid(req),id=Number(req.params.id);const a=db.prepare(`SELECT * FROM v2_loaner_assignments WHERE id=? AND shop_id=? AND returned_at IS NULL`).get(id,s);if(!a)return res.status(404).json({error:'Open loaner assignment not found.'});const tx=db.transaction(()=>{db.prepare(`UPDATE v2_loaner_assignments SET returned_at=CURRENT_TIMESTAMP WHERE id=? AND shop_id=?`).run(id,s);db.prepare(`UPDATE v2_loaners SET status='available' WHERE id=? AND shop_id=?`).run(a.loaner_id,s);});tx();res.json({ok:true});});
}
module.exports={installV2Loaners};
