function installV2Notes(app,db,{requireLogin}){
 const sid=req=>Number(req.session.employee.shop_id),eid=req=>Number(req.session.employee.id);
 db.exec(`CREATE TABLE IF NOT EXISTS v2_ro_notes(id INTEGER PRIMARY KEY AUTOINCREMENT,shop_id INTEGER NOT NULL,repair_order_id INTEGER NOT NULL,employee_id INTEGER,note TEXT NOT NULL,pinned INTEGER NOT NULL DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS idx_v2_ro_notes_ro ON v2_ro_notes(shop_id,repair_order_id,created_at);`);
 const owns=(shop,id)=>db.prepare(`SELECT id FROM repair_orders WHERE id=? AND shop_id=?`).get(id,shop);
 app.get('/api/v2/repair-orders/:id/notes',requireLogin,(req,res)=>{const shop=sid(req),id=Number(req.params.id);if(!owns(shop,id))return res.status(404).json({error:'Repair order not found.'});res.json(db.prepare(`SELECT n.id,n.note,n.pinned,n.created_at,e.name employee_name FROM v2_ro_notes n LEFT JOIN employees e ON e.id=n.employee_id AND e.shop_id=n.shop_id WHERE n.shop_id=? AND n.repair_order_id=? ORDER BY n.pinned DESC,n.created_at DESC,n.id DESC`).all(shop,id));});
 app.post('/api/v2/repair-orders/:id/notes',requireLogin,(req,res)=>{const shop=sid(req),id=Number(req.params.id);if(!owns(shop,id))return res.status(404).json({error:'Repair order not found.'});const note=String(req.body.note||'').trim();if(!note)return res.status(400).json({error:'Note is required.'});const pinned=req.body.pinned?1:0;const info=db.prepare(`INSERT INTO v2_ro_notes(shop_id,repair_order_id,employee_id,note,pinned)VALUES(?,?,?,?,?)`).run(shop,id,eid(req),note,pinned);db.prepare(`INSERT INTO audit_log(shop_id,employee_id,action,entity_type,entity_id,details)VALUES(?,?,?,?,?,?)`).run(shop,eid(req),'repair_order.internal_note','repair_order',id,JSON.stringify({note_id:info.lastInsertRowid,pinned:Boolean(pinned)}));res.json({ok:true,id:info.lastInsertRowid});});
 app.patch('/api/v2/repair-orders/:roId/notes/:noteId',requireLogin,(req,res)=>{const shop=sid(req),ro=Number(req.params.roId),id=Number(req.params.noteId);if(!owns(shop,ro))return res.status(404).json({error:'Repair order not found.'});const row=db.prepare(`SELECT * FROM v2_ro_notes WHERE id=? AND repair_order_id=? AND shop_id=?`).get(id,ro,shop);if(!row)return res.status(404).json({error:'Note not found.'});const pinned=req.body.pinned===undefined?row.pinned:(req.body.pinned?1:0);db.prepare(`UPDATE v2_ro_notes SET pinned=? WHERE id=? AND shop_id=?`).run(pinned,id,shop);res.json({ok:true});});
}
module.exports={installV2Notes};
