const {permissionMiddleware}=require('./v2-permissions');
function installV2Notes(app,db,{requireLogin}){
 const sid=req=>Number(req.session.employee.shop_id),eid=req=>Number(req.session.employee.id),requireRepairOrders=permissionMiddleware('repair_orders');
 db.exec(`CREATE TABLE IF NOT EXISTS v2_ro_notes(id INTEGER PRIMARY KEY AUTOINCREMENT,shop_id INTEGER NOT NULL,repair_order_id INTEGER NOT NULL,employee_id INTEGER,note TEXT NOT NULL,pinned INTEGER NOT NULL DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS idx_v2_ro_notes_ro ON v2_ro_notes(shop_id,repair_order_id,created_at);`);
 const owns=(shop,id)=>db.prepare(`SELECT id,workflow_status FROM repair_orders WHERE id=? AND shop_id=?`).get(id,shop);
 app.get('/api/v2/repair-orders/:id/notes',requireLogin,requireRepairOrders,(req,res)=>{const shop=sid(req),id=Number(req.params.id);if(!owns(shop,id))return res.status(404).json({error:'Repair order not found.'});res.json(db.prepare(`SELECT n.id,n.note,n.pinned,n.created_at,e.name employee_name FROM v2_ro_notes n LEFT JOIN employees e ON e.id=n.employee_id AND e.shop_id=n.shop_id WHERE n.shop_id=? AND n.repair_order_id=? ORDER BY n.pinned DESC,n.created_at DESC,n.id DESC LIMIT 500`).all(shop,id));});
 app.post('/api/v2/repair-orders/:id/notes',requireLogin,requireRepairOrders,(req,res)=>{const shop=sid(req),id=Number(req.params.id),ro=owns(shop,id);if(!ro)return res.status(404).json({error:'Repair order not found.'});if(String(ro.workflow_status||'').toLowerCase()==='delivered')return res.status(409).json({error:'Cannot add internal notes after vehicle delivery.'});const note=String(req.body.note||'').trim().slice(0,5000);if(!note)return res.status(400).json({error:'Note is required.'});const pinned=req.body.pinned?1:0;const tx=db.transaction(()=>{const info=db.prepare(`INSERT INTO v2_ro_notes(shop_id,repair_order_id,employee_id,note,pinned)VALUES(?,?,?,?,?)`).run(shop,id,eid(req),note,pinned);db.prepare(`INSERT INTO audit_log(shop_id,employee_id,action,entity_type,entity_id,details)VALUES(?,?,?,?,?,?)`).run(shop,eid(req),'repair_order.internal_note','repair_order',id,JSON.stringify({note_id:info.lastInsertRowid,pinned:Boolean(pinned)}));return info.lastInsertRowid;});const noteId=tx();res.json({ok:true,id:noteId});});
 app.patch('/api/v2/repair-orders/:roId/notes/:noteId',requireLogin,requireRepairOrders,(req,res)=>{const shop=sid(req),ro=Number(req.params.roId),id=Number(req.params.noteId),order=owns(shop,ro);if(!order)return res.status(404).json({error:'Repair order not found.'});if(String(order.workflow_status||'').toLowerCase()==='delivered')return res.status(409).json({error:'Cannot change internal notes after vehicle delivery.'});const row=db.prepare(`SELECT * FROM v2_ro_notes WHERE id=? AND repair_order_id=? AND shop_id=?`).get(id,ro,shop);if(!row)return res.status(404).json({error:'Note not found.'});const pinned=req.body.pinned===undefined?row.pinned:(req.body.pinned?1:0);if(pinned===row.pinned)return res.json({ok:true,unchanged:true});const tx=db.transaction(()=>{db.prepare(`UPDATE v2_ro_notes SET pinned=? WHERE id=? AND repair_order_id=? AND shop_id=?`).run(pinned,id,ro,shop);db.prepare(`INSERT INTO audit_log(shop_id,employee_id,action,entity_type,entity_id,details)VALUES(?,?,?,?,?,?)`).run(shop,eid(req),'repair_order.note_pin_changed','repair_order',ro,JSON.stringify({note_id:id,previous_pinned:Boolean(row.pinned),pinned:Boolean(pinned)}));});tx();res.json({ok:true});});
}
module.exports={installV2Notes};
