const {permissionMiddleware,loadCurrentEmployee}=require('./v2-permissions');
function installV2Search(app,db,{requireLogin}){
 if(!app||!db)throw new Error('V2 search requires app and db.');if(!requireLogin)throw new Error('V2 search requires authentication middleware.');
 const requireRepairOrders=permissionMiddleware('repair_orders',db),empty=()=>({customers:[],vehicles:[],repair_orders:[]}),validId=v=>Number.isInteger(v)&&v>0;
 app.get('/api/v2/search',requireLogin,requireRepairOrders,(req,res)=>{try{
   const employee=req.v2Employee||loadCurrentEmployee(db,req.session?.employee),s=Number(employee?.shop_id||0),e=Number(employee?.id||0);if(!employee||!validId(s)||!validId(e))return res.status(401).json({error:'Employee session is no longer valid for this shop.'});const live=loadCurrentEmployee(db,req.session?.employee);if(!live||Number(live.id)!==e||Number(live.shop_id)!==s)return res.status(401).json({error:'Employee session is no longer valid for this shop.'});req.v2Employee=employee;req.v2ShopId=s;
   res.set('Cache-Control','no-store, private, max-age=0');res.set('Pragma','no-cache');res.set('Expires','0');res.set('X-Content-Type-Options','nosniff');
   const raw=String(req.query?.q||'').trim().slice(0,120);if(raw.length<2)return res.json(empty());const escaped=raw.replace(/[\\%_]/g,m=>'\\'+m),q=`%${escaped}%`,numeric=/^\d{1,10}$/.test(raw)?Number(raw):null,id=Number.isSafeInteger(numeric)&&numeric>0?numeric:-1;
   const customers=db.prepare(`SELECT id,name,phone,email FROM customers WHERE shop_id=? AND (name LIKE ? ESCAPE '\\' OR phone LIKE ? ESCAPE '\\' OR email LIKE ? ESCAPE '\\') ORDER BY name,id LIMIT 20`).all(s,q,q,q);
   const vehicles=db.prepare(`SELECT v.id,v.customer_id,v.year,v.make,v.model,v.vin,v.license_plate,c.name customer_name FROM vehicles v JOIN customers c ON c.id=v.customer_id AND c.shop_id=v.shop_id WHERE v.shop_id=? AND (v.make LIKE ? ESCAPE '\\' OR v.model LIKE ? ESCAPE '\\' OR v.vin LIKE ? ESCAPE '\\' OR v.license_plate LIKE ? ESCAPE '\\' OR CAST(v.year AS TEXT) LIKE ? ESCAPE '\\' OR c.name LIKE ? ESCAPE '\\') ORDER BY v.id DESC LIMIT 20`).all(s,q,q,q,q,q,q);
   const ros=db.prepare(`SELECT r.id,r.status,r.workflow_status,r.created_at,c.id customer_id,c.name customer_name,v.year,v.make,v.model,v.vin,v.license_plate FROM repair_orders r JOIN customers c ON c.id=r.customer_id AND c.shop_id=r.shop_id LEFT JOIN vehicles v ON v.id=r.vehicle_id AND v.shop_id=r.shop_id WHERE r.shop_id=? AND (r.vehicle_id IS NULL OR v.id IS NOT NULL) AND (r.id=? OR c.name LIKE ? ESCAPE '\\' OR c.phone LIKE ? ESCAPE '\\' OR c.email LIKE ? ESCAPE '\\' OR v.vin LIKE ? ESCAPE '\\' OR v.license_plate LIKE ? ESCAPE '\\' OR v.make LIKE ? ESCAPE '\\' OR v.model LIKE ? ESCAPE '\\') ORDER BY r.id DESC LIMIT 30`).all(s,id,q,q,q,q,q,q,q);
   return res.json({customers,vehicles,repair_orders:ros});
  }catch(err){console.error('Garavex V2 search error:',err);return res.status(500).json({error:'Search could not be completed.'});}});
}
module.exports={installV2Search};
