const {permissionMiddleware}=require('./v2-permissions');
function installV2Tasks(app,db,{requireLogin}){
 const sid=req=>Number(req.session.employee.shop_id),eid=req=>Number(req.session.employee.id),requireTasks=permissionMiddleware('tasks');
 db.exec(`CREATE TABLE IF NOT EXISTS v2_tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,shop_id INTEGER NOT NULL,repair_order_id INTEGER,assigned_to INTEGER,title TEXT NOT NULL,details TEXT,priority TEXT NOT NULL DEFAULT 'normal',due_at DATETIME,status TEXT NOT NULL DEFAULT 'open',created_by INTEGER,completed_by INTEGER,completed_at DATETIME,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS idx_v2_tasks_shop_status ON v2_tasks(shop_id,status,due_at);`);
 app.get('/api/v2/tasks',requireLogin,requireTasks,(req,res)=>{const s=sid(req),status=String(req.query.status||'open');if(!['open','completed','all'].includes(status))return res.status(400).json({error:'Invalid task status filter.'});res.json(db.prepare(`SELECT t.*,a.name assigned_name,c.name created_name,r.workflow_status,cu.name customer_name,v.year,v.make,v.model,CASE WHEN t.status='open' AND t.due_at IS NOT NULL AND datetime(t.due_at)<datetime('now') THEN 1 ELSE 0 END overdue FROM v2_tasks t LEFT JOIN employees a ON a.id=t.assigned_to AND a.shop_id=t.shop_id LEFT JOIN employees c ON c.id=t.created_by AND c.shop_id=t.shop_id LEFT JOIN repair_orders r ON r.id=t.repair_order_id AND r.shop_id=t.shop_id LEFT JOIN customers cu ON cu.id=r.customer_id AND cu.shop_id=r.shop_id LEFT JOIN vehicles v ON v.id=r.vehicle_id AND v.shop_id=r.shop_id WHERE t.shop_id=? AND (?='all' OR t.status=?) ORDER BY overdue DESC,CASE t.priority WHEN 'urgent' THEN 0 WHEN 'high' THEN 1 ELSE 2 END,t.due_at IS NULL,t.due_at,t.id DESC LIMIT 200`).all(s,status,status));});
 app.post('/api/v2/tasks',requireLogin,requireTasks,(req,res)=>{const s=sid(req),title=String(req.body.title||'').trim(),details=String(req.body.details||'').trim();if(!title)return res.status(400).json({error:'Task title is required.'});const priority=['normal','high','urgent'].includes(req.body.priority)?req.body.priority:'normal';const assigned=Number(req.body.assigned_to)||null;if(assigned&&!db.prepare(`SELECT id FROM employees WHERE id=? AND shop_id=?`).get(assigned,s))return res.status(400).json({error:'Assigned employee is not in this shop.'});const ro=Number(req.body.repair_order_id)||null;if(ro){const order=db.prepare(`SELECT id,workflow_status FROM repair_orders WHERE id=? AND shop_id=?`).get(ro,s);if(!order)return res.status(400).json({error:'Repair order not found.'});if(String(order.workflow_status||'').toLowerCase()==='delivered')return res.status(409).json({error:'Cannot create a task for a delivered repair order.'});}const due=req.body.due_at||null;if(due&&Number.isNaN(Date.parse(due)))return res.status(400).json({error:'Task due date is invalid.'});const tx=db.transaction(()=>{const info=db.prepare(`INSERT INTO v2_tasks(shop_id,repair_order_id,assigned_to,title,details,priority,due_at,created_by)VALUES(?,?,?,?,?,?,?,?)`).run(s,ro,assigned,title.slice(0,160),details.slice(0,2000),priority,due,eid(req));db.prepare(`INSERT INTO audit_log(shop_id,employee_id,action,entity_type,entity_id,details)VALUES(?,?,?,?,?,?)`).run(s,eid(req),'task.created',ro?'repair_order':'task',ro||info.lastInsertRowid,JSON.stringify({task_id:info.lastInsertRowid,title:title.slice(0,160),assigned_to:assigned,priority,due_at:due}));return info.lastInsertRowid;});const id=tx();res.json({ok:true,id});});
 app.patch('/api/v2/tasks/:id/complete',requireLogin,requireTasks,(req,res)=>{const s=sid(req),id=Number(req.params.id),task=db.prepare(`SELECT * FROM v2_tasks WHERE id=? AND shop_id=? AND status='open'`).get(id,s);if(!task)return res.status(404).json({error:'Open task not found.'});const tx=db.transaction(()=>{db.prepare(`UPDATE v2_tasks SET status='completed',completed_by=?,completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND shop_id=? AND status='open'`).run(eid(req),id,s);db.prepare(`INSERT INTO audit_log(shop_id,employee_id,action,entity_type,entity_id,details)VALUES(?,?,?,?,?,?)`).run(s,eid(req),'task.completed',task.repair_order_id?'repair_order':'task',task.repair_order_id||id,JSON.stringify({task_id:id,title:task.title,assigned_to:task.assigned_to}));});tx();res.json({ok:true});});
}
module.exports={installV2Tasks};
