const {permissionMiddleware}=require('./v2-permissions');
function installV2Time(app,db,{requireLogin,requireOwner}){
 const sid=req=>Number(req.session.employee.shop_id),eid=req=>Number(req.session.employee.id),requireTime=permissionMiddleware('time_tracking');
 const validId=x=>Number.isInteger(x)&&x>0;
 app.post('/api/v2/time/clock-in',requireLogin,requireTime,(req,res)=>{const s=sid(req),e=eid(req),ro=Number(req.body.repair_order_id||0)||null,item=Number(req.body.repair_order_item_id||0)||null;if(ro&&!validId(ro))return res.status(400).json({error:'Valid repair order ID is required.'});if(item&&!validId(item))return res.status(400).json({error:'Valid repair order item ID is required.'});if(ro){const order=db.prepare(`SELECT id,workflow_status FROM repair_orders WHERE id=? AND shop_id=?`).get(ro,s);if(!order)return res.status(404).json({error:'Repair order not found.'});if(String(order.workflow_status||'').toLowerCase()==='delivered')return res.status(409).json({error:'Cannot clock into a delivered repair order.'});}if(item){if(!ro)return res.status(400).json({error:'Repair order is required when clocking into a line item.'});if(!db.prepare(`SELECT i.id FROM repair_order_items i JOIN repair_orders r ON r.id=i.repair_order_id WHERE i.id=? AND i.repair_order_id=? AND r.shop_id=?`).get(item,ro,s))return res.status(404).json({error:'Repair order item not found.'});}const notes=String(req.body.notes||'').trim().slice(0,1000);const tx=db.transaction(()=>{const info=db.prepare(`INSERT INTO technician_time_entries(shop_id,employee_id,repair_order_id,repair_order_item_id,notes)VALUES(?,?,?,?,?)`).run(s,e,ro,item,notes||null);db.prepare(`INSERT INTO audit_log(shop_id,employee_id,action,entity_type,entity_id,details)VALUES(?,?,?,?,?,?)`).run(s,e,'time.clock_in','time_entry',info.lastInsertRowid,JSON.stringify({repair_order_id:ro,repair_order_item_id:item}));return info.lastInsertRowid;});try{const id=tx();res.json({ok:true,id});}catch(err){if(String(err.message).includes('UNIQUE'))return res.status(409).json({error:'You are already clocked in.'});throw err;}});
 app.post('/api/v2/time/clock-out',requireLogin,requireTime,(req,res)=>{const s=sid(req),e=eid(req),row=db.prepare(`SELECT * FROM technician_time_entries WHERE shop_id=? AND employee_id=? AND clock_out IS NULL ORDER BY id DESC LIMIT 1`).get(s,e);if(!row)return res.status(404).json({error:'No active time entry.'});const tx=db.transaction(()=>{const changed=db.prepare(`UPDATE technician_time_entries SET clock_out=CURRENT_TIMESTAMP,minutes=MAX(1,ROUND((julianday(CURRENT_TIMESTAMP)-julianday(clock_in))*1440)) WHERE id=? AND shop_id=? AND employee_id=? AND clock_out IS NULL`).run(row.id,s,e);if(changed.changes!==1)throw new Error('Time entry changed before clock-out.');const done=db.prepare(`SELECT minutes,clock_out FROM technician_time_entries WHERE id=? AND shop_id=?`).get(row.id,s);db.prepare(`INSERT INTO audit_log(shop_id,employee_id,action,entity_type,entity_id,details)VALUES(?,?,?,?,?,?)`).run(s,e,'time.clock_out','time_entry',row.id,JSON.stringify({repair_order_id:row.repair_order_id,minutes:done.minutes}));return done;});try{res.json({ok:true,...tx()});}catch(err){return res.status(409).json({error:'Time entry was already clocked out.'});}});
 app.get('/api/v2/time/active',requireLogin,requireTime,(req,res)=>{const s=sid(req),e=eid(req);res.json(db.prepare(`SELECT t.id,t.repair_order_id,t.repair_order_item_id,t.clock_in,t.notes,c.name customer_name,v.year,v.make,v.model FROM technician_time_entries t LEFT JOIN repair_orders r ON r.id=t.repair_order_id AND r.shop_id=t.shop_id LEFT JOIN customers c ON c.id=r.customer_id AND c.shop_id=r.shop_id LEFT JOIN vehicles v ON v.id=r.vehicle_id AND v.shop_id=r.shop_id WHERE t.shop_id=? AND t.employee_id=? AND t.clock_out IS NULL ORDER BY t.id DESC LIMIT 1`).get(s,e)||null);});
 app.get('/api/v2/time/recent',requireLogin,requireTime,(req,res)=>{const s=sid(req),e=eid(req);res.json(db.prepare(`SELECT id,repair_order_id,repair_order_item_id,clock_in,clock_out,minutes,notes FROM technician_time_entries WHERE shop_id=? AND employee_id=? ORDER BY clock_in DESC,id DESC LIMIT 100`).all(s,e));});
 app.get('/api/v2/time/shop',requireLogin,requireOwner,(req,res)=>{const s=sid(req);res.json(db.prepare(`SELECT t.id,t.employee_id,e.name employee_name,t.repair_order_id,t.clock_in,t.clock_out,t.minutes,t.notes FROM technician_time_entries t JOIN employees e ON e.id=t.employee_id AND e.shop_id=t.shop_id WHERE t.shop_id=? ORDER BY t.clock_in DESC,t.id DESC LIMIT 500`).all(s));});
}
module.exports={installV2Time};
